Added LibreWolf
pluja/awesome-privacy pull request #30
Opened 2021-05-24 10:09 UTC by tuxsudo12

Added LibreWolf to Desktop list under Web Browser
This is my first pull request and I'm new to Git so let me know if I did something wrong, thank you

2021-05-24 15:12 UTC, MonsieurBibo commented
Good Browser. Maybe this branch needs to be reworked because LibreWolf is a fork of Firefox.

2021-05-25 06:28 UTC, pluja commented
Could you add it as a nested item under Firefox?

2021-05-30 06:29 UTC, pluja requested changes

2021-05-30 06:29 UTC, pluja commented on README.md
> +- [LibreWolf](https://librewolf-community.gitlab.io/)
Can you change it to a nested element below Firefox and mention it is a privacy-focused fork? Just like this:

* Firefox
    * LibreWolf - Privacy-focused Firefox fork.

2021-05-30 06:54 UTC, a1300 commented on README.md
> +- [LibreWolf](https://librewolf-community.gitlab.io/)
```suggestion
- [Firefox](https://www.mozilla.org/en-US/firefox/new/)
  - [LibreWolf](https://librewolf-community.gitlab.io/) - Privacy-focused Firefox fork.
- [Ungoogled Chromium](https://ungoogled-software.github.io/)
- [Tor Browser](https://www.torproject.org/)
```

2021-06-02 16:09 UTC, pluja approved these changes

2021-06-02 16:09 UTC, merged

2021-06-06 05:22 UTC, tuxsudo12 commented
Got caught busy with work past couple weeks forgot to check up on my pull request, how did you manage to make the change while simultaneously merging this commit?

2021-06-06 10:00 UTC, a1300 commented
@tuxsudo12 one can propose changes with a `suggestion` code block. They can be then committed by the maintainer. 

![](https://docs.github.com/assets/images/help/pull_requests/suggestion-block.png)